site_name: "Abhilash Sagar — Docs"
site_url: "https://abhilashsagar.github.io"

theme:
  name: material
  features:
    - navigation.instant
    - navigation.expand
    - navigation.sections
    - navigation.top
    - search.highlight
    - search.suggest

plugins:
  - search
  - blog

nav:
  - Home: index.md
  - Linux Device Drivers:
      - Introduction: linuxdd/
  - Yocto:
      - Introduction: yocto/
  - RTOS:
      - Introduction: rtos/
